# Generated by Django 6.0.5 on 2026-05-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('birth_day', models.DateField()),
                ('monthly_listeners', models.IntegerField()),
                ('bio', models.CharField(max_length=400)),
                ('started_making_music', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateField()),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('artis_name', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateField()),
                ('genre_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
            ],
        ),
    ]
