# Generated by Django 6.0.5 on 2026-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artis_name',
            field=models.CharField(max_length=50),
        ),
    ]
