# Generated by Django 6.0.5 on 2026-05-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('song_title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('artis_name', models.CharField(max_length=50, unique=True)),
                ('genre_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
            ],
        ),
    ]
